//! All bundled modules. Each module gets its own file.

pub mod aboutdiscowithlove;
pub mod alterportal;
pub mod archive_org;
pub mod blogspot;
pub mod burningtheground;
pub mod butterboy;
pub mod ccmixter;
pub mod classicalmusicdownload;
pub mod coreradio;
pub mod dance_music;
pub mod deadpulpit;
pub mod dieordiy2;
pub mod discogc;
pub mod discografias;
pub mod dle_blog;
pub mod edmwaves;
pub mod ektoplazm;
pub mod essentialhouse;
pub mod exystence;
pub mod ezhevika;
pub mod flacmusic;
pub mod flatblackandclassical;
pub mod flights1000;
pub mod foggynotionflac;
pub mod fondsound;
pub mod forwardwiththesong;
pub mod fpftp;
pub mod freemp3cloud;
pub mod globaldjmix;
pub mod glorybeats;
pub mod goldhiphop;
pub mod grimearchive;
pub mod hiphop94;
pub mod hiphopa;
pub mod hipstrumentals;
pub mod inconstantsol;
pub mod intmusic;
pub mod iplusfree;
pub mod josephbarulho;
pub mod kpopdownloadscmm;
pub mod ktimusic;
pub mod losslessalbums;
pub mod losslessmusic;
pub mod lostsongshc;
pub mod lrclib;
pub mod lyrics_ovh;
pub mod lyrist;
pub mod madrotter;
pub mod meetinginmusic;
pub mod metalminos;
pub mod mp3db;
pub mod musicrepublicworld;
pub mod musicrider;
pub mod musify;
pub mod musixmatch;
pub mod nathannothinsez;
pub mod newalbumreleases;
pub mod nodata;
pub mod nuclearholocaust;
pub mod oldschoolmetalmusicz;
pub mod onetechno;
pub mod onetrance;
pub mod paradiseofgaragecomps;
pub mod primitiveofferings;
pub mod progrockvintage;
pub mod psyfp;
pub mod punkcata;
pub mod rapload;
pub mod rapwarfam;
pub mod registry;
pub mod sophiesfloorboard;
pub mod soundclick;
pub mod soundcloud;
pub mod stubs;
pub mod systemsofromance;
pub mod takemetal;
pub mod tancpol;
pub mod tapeattack;
pub mod technicaldeathmetal;
pub mod themfire;
pub mod tomlehrersongs;
pub mod toneandwave;
pub mod tsquareplaza;
pub mod urbanaspirines;
pub mod wordpress_blog;
pub mod youtube;
pub mod zvu4it;

pub fn md5_hex(input: &[u8]) -> String {
    use md5::Digest;
    let mut h = md5::Md5::new();
    h.update(input);
    format!("{:x}", h.finalize())
}
